version: '3.8'
services:
  converter:
    image: sgbj/versed:latest
    container_name: libreoffice-converter
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped