using System.Text.Json.Serialization;
using ConfluenceLite.Api.DTOs;
using ConfluenceLite.Api.Services;
using ConfluenceLite.Api.Middleware;

namespace ConfluenceLite.Api.Mappers;

/// <summary>
/// JSON序列化源生成器上下文 - Native AOT 必需
/// </summary>
[JsonSerializable(typeof(ApiResponse<object>))]
[JsonSerializable(typeof(ApiResponse<string>))]
[JsonSerializable(typeof(ApiResponse<int>))]
[JsonSerializable(typeof(ApiResponse<bool>))]
[JsonSerializable(typeof(ApiResponse<UserDto>))]
[JsonSerializable(typeof(ApiResponse<WorkspaceDto>))]
[JsonSerializable(typeof(ApiResponse<PageDto>))]
[JsonSerializable(typeof(ApiResponse<CommentDto>))]
[JsonSerializable(typeof(ApiResponse<LoginResponse>))]
[JsonSerializable(typeof(ApiResponse<List<UserDto>>))]
[JsonSerializable(typeof(ApiResponse<List<WorkspaceDto>>))]
[JsonSerializable(typeof(ApiResponse<List<PageDto>>))]
[JsonSerializable(typeof(ApiResponse<List<PageTreeNodeDto>>))]
[JsonSerializable(typeof(ApiResponse<List<CommentDto>>))]
[JsonSerializable(typeof(ApiResponse<PageVersionDto>))]
[JsonSerializable(typeof(ApiResponse<List<PageVersionListDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<UserDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<WorkspaceDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<PageDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<CommentDto>>))]
[JsonSerializable(typeof(ApiResponse<AttachmentDto>))]
[JsonSerializable(typeof(ApiResponse<List<AttachmentListItemDto>>))]
[JsonSerializable(typeof(PagedResponse<UserDto>))]
[JsonSerializable(typeof(PagedResponse<WorkspaceDto>))]
[JsonSerializable(typeof(PagedResponse<PageDto>))]
[JsonSerializable(typeof(PagedResponse<CommentDto>))]
[JsonSerializable(typeof(UserDto))]
[JsonSerializable(typeof(List<UserDto>))]
[JsonSerializable(typeof(WorkspaceDto))]
[JsonSerializable(typeof(List<WorkspaceDto>))]
[JsonSerializable(typeof(PageDto))]
[JsonSerializable(typeof(List<PageDto>))]
[JsonSerializable(typeof(PageTreeNodeDto))]
[JsonSerializable(typeof(List<PageTreeNodeDto>))]
[JsonSerializable(typeof(CommentDto))]
[JsonSerializable(typeof(List<CommentDto>))]
[JsonSerializable(typeof(PageVersionDto))]
[JsonSerializable(typeof(List<PageVersionListDto>))]
[JsonSerializable(typeof(AttachmentDto))]
[JsonSerializable(typeof(AttachmentListItemDto))]
[JsonSerializable(typeof(UserSummaryDto))]
[JsonSerializable(typeof(WorkspaceSummaryDto))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(CreateWorkspaceRequest))]
[JsonSerializable(typeof(UpdateWorkspaceRequest))]
[JsonSerializable(typeof(CreatePageRequest))]
[JsonSerializable(typeof(UpdatePageRequest))]
[JsonSerializable(typeof(CreateCommentRequest))]
[JsonSerializable(typeof(UpdateCommentRequest))]
[JsonSerializable(typeof(PagedRequest))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(ApiInfoResponse))]
[JsonSerializable(typeof(ApiEndpoints))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(ApiResponse<SetupStatusResponse>))]
[JsonSerializable(typeof(ApiResponse<TestConnectionResponse>))]
[JsonSerializable(typeof(SetupStatusResponse))]
[JsonSerializable(typeof(TestConnectionResponse))]
[JsonSerializable(typeof(SetupResponse))]
[JsonSerializable(typeof(DatabaseConfigRequest))]
[JsonSerializable(typeof(SetupRequest))]
[JsonSerializable(typeof(InstalledInfo))]
[JsonSerializable(typeof(ActivityDto))]
[JsonSerializable(typeof(List<ActivityDto>))]
[JsonSerializable(typeof(ApiResponse<SetupResponse>))]
[JsonSerializable(typeof(ApiResponse<OfficePreviewConfigDto>))]
[JsonSerializable(typeof(OfficePreviewConfigDto))]
[JsonSerializable(typeof(SiteConfigDto))]
[JsonSerializable(typeof(DisplayConfigDto))]
[JsonSerializable(typeof(SiteInfoDto))]
[JsonSerializable(typeof(ApiResponse<SiteConfigDto>))]
[JsonSerializable(typeof(ApiResponse<DisplayConfigDto>))]
[JsonSerializable(typeof(ApiResponse<SiteInfoDto>))]
[JsonSerializable(typeof(SecurityConfigDto))]
[JsonSerializable(typeof(ApiResponse<SecurityConfigDto>))]
[JsonSerializable(typeof(MailConfigDto))]
[JsonSerializable(typeof(ApiResponse<MailConfigDto>))]
[JsonSerializable(typeof(AuthConfigDto))]
[JsonSerializable(typeof(ApiResponse<AuthConfigDto>))]
// User Group
[JsonSerializable(typeof(UserGroupDto))]
[JsonSerializable(typeof(List<UserGroupDto>))]
[JsonSerializable(typeof(CreateUserGroupRequest))]
[JsonSerializable(typeof(UpdateUserGroupRequest))]
[JsonSerializable(typeof(AddGroupMembersRequest))]
[JsonSerializable(typeof(UserGroupMemberDto))]
[JsonSerializable(typeof(UserGroupMembersResponse))]
[JsonSerializable(typeof(ApiResponse<UserGroupDto>))]
[JsonSerializable(typeof(ApiResponse<UserGroupMembersResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<UserGroupDto>>))]
[JsonSerializable(typeof(PagedResponse<UserGroupDto>))]
// System Info
[JsonSerializable(typeof(SystemInfoDto))]
[JsonSerializable(typeof(CpuInfoDto))]
[JsonSerializable(typeof(MemoryInfoDto))]
[JsonSerializable(typeof(DatabaseInfoDto))]
[JsonSerializable(typeof(SystemStatsDto))]
[JsonSerializable(typeof(ApiResponse<SystemInfoDto>))]
[JsonSerializable(typeof(ApiResponse<SystemStatsDto>))]
// Log
[JsonSerializable(typeof(LogEntryDto))]
[JsonSerializable(typeof(List<LogEntryDto>))]
[JsonSerializable(typeof(LogQueryRequest))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<LogEntryDto>>))]
[JsonSerializable(typeof(PagedResponse<LogEntryDto>))]
// Cache
[JsonSerializable(typeof(CacheStatsDto))]
[JsonSerializable(typeof(CacheTypeDto))]
[JsonSerializable(typeof(List<CacheTypeDto>))]
[JsonSerializable(typeof(CacheKeyDto))]
[JsonSerializable(typeof(List<CacheKeyDto>))]
[JsonSerializable(typeof(ApiResponse<CacheStatsDto>))]
[JsonSerializable(typeof(ApiResponse<List<CacheTypeDto>>))]
[JsonSerializable(typeof(ApiResponse<List<CacheKeyDto>>))]
// Jobs
[JsonSerializable(typeof(ScheduledJobDto))]
[JsonSerializable(typeof(List<ScheduledJobDto>))]
[JsonSerializable(typeof(JobExecutionDto))]
[JsonSerializable(typeof(List<JobExecutionDto>))]
[JsonSerializable(typeof(CreateJobRequest))]
[JsonSerializable(typeof(UpdateJobRequest))]
[JsonSerializable(typeof(JobStatsDto))]
[JsonSerializable(typeof(ApiResponse<List<ScheduledJobDto>>))]
[JsonSerializable(typeof(ApiResponse<ScheduledJobDto>))]
[JsonSerializable(typeof(ApiResponse<List<JobExecutionDto>>))]
[JsonSerializable(typeof(ApiResponse<JobStatsDto>))]
// Backup
[JsonSerializable(typeof(BackupDto))]
[JsonSerializable(typeof(List<BackupDto>))]
[JsonSerializable(typeof(CreateBackupRequest))]
[JsonSerializable(typeof(RestoreBackupRequest))]
[JsonSerializable(typeof(BackupConfigDto))]
[JsonSerializable(typeof(ApiResponse<BackupConfigDto>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(ApiResponse<BackupDto>))]
[JsonSerializable(typeof(ApiResponse<List<BackupDto>>))]
// Confluence Import
[JsonSerializable(typeof(ImportTaskDto))]
[JsonSerializable(typeof(List<ImportTaskDto>))]
[JsonSerializable(typeof(ImportProgressDto))]
[JsonSerializable(typeof(ImportOptionsRequest))]
[JsonSerializable(typeof(ApiResponse<ImportTaskDto>))]
[JsonSerializable(typeof(ApiResponse<List<ImportTaskDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<ImportTaskDto>>))]
[JsonSerializable(typeof(PagedResponse<ImportTaskDto>))]
[JsonSerializable(typeof(ConfluenceLite.Api.Models.ImportOptions))]
[JsonSerializable(typeof(ConfluenceLite.Api.Models.ImportProgress))]
// Audit Log
[JsonSerializable(typeof(AuditLogEntry))]
[JsonSerializable(typeof(AuditChangeDetails))]
[JsonSerializable(typeof(ChangeDetail))]
// OIDC
[JsonSerializable(typeof(OidcDiscoveryConfig))]
[JsonSerializable(typeof(OidcTokenResponse))]
[JsonSerializable(typeof(OidcUserInfo))]
// Auth Middleware
[JsonSerializable(typeof(UnauthorizedResponse))]
// Search
[JsonSerializable(typeof(SearchSuggestionDto))]
[JsonSerializable(typeof(List<SearchSuggestionDto>))]
[JsonSerializable(typeof(SearchResultDto))]
[JsonSerializable(typeof(List<SearchResultDto>))]
[JsonSerializable(typeof(ApiResponse<List<RecentDto>>))]
[JsonSerializable(typeof(RecentDto))]
[JsonSerializable(typeof(List<RecentDto>))]
[JsonSerializable(typeof(ApiResponse<List<SearchSuggestionDto>>))]
[JsonSerializable(typeof(ApiResponse<List<SearchResultDto>>))]
// Share
[JsonSerializable(typeof(ShareDto))]
[JsonSerializable(typeof(List<ShareDto>))]
[JsonSerializable(typeof(PublicShareInfoDto))]
[JsonSerializable(typeof(SharePageInfoDto))]
[JsonSerializable(typeof(CreateShareRequest))]
[JsonSerializable(typeof(UpdateShareRequest))]
[JsonSerializable(typeof(UpdateSharePageRequest))]
[JsonSerializable(typeof(ApiResponse<ShareDto>))]
[JsonSerializable(typeof(ApiResponse<List<ShareDto>>))]
[JsonSerializable(typeof(ApiResponse<PublicShareInfoDto>))]
// Batch Sort
[JsonSerializable(typeof(BatchSortPageItem))]
[JsonSerializable(typeof(List<BatchSortPageItem>))]
[JsonSerializable(typeof(BatchSortPageRequest))]
// Move Page
[JsonSerializable(typeof(MovePageRequest))]
public partial class AppJsonContext : JsonSerializerContext
{
}
