using System.Text.Json.Serialization;
using ConfluenceLite.Api.DTOs;

namespace ConfluenceLite.Api.Mappers;

/// <summary>
/// JSON序列化源生成器上下文 - Native AOT 必需
/// </summary>
[JsonSerializable(typeof(ApiResponse<object>))]
[JsonSerializable(typeof(ApiResponse<string>))]
[JsonSerializable(typeof(ApiResponse<int>))]
[JsonSerializable(typeof(ApiResponse<bool>))]
[JsonSerializable(typeof(ApiResponse<UserDto>))]
[JsonSerializable(typeof(ApiResponse<WorkspaceDto>))]
[JsonSerializable(typeof(ApiResponse<PageDto>))]
[JsonSerializable(typeof(ApiResponse<CommentDto>))]
[JsonSerializable(typeof(ApiResponse<LoginResponse>))]
[JsonSerializable(typeof(ApiResponse<List<UserDto>>))]
[JsonSerializable(typeof(ApiResponse<List<WorkspaceDto>>))]
[JsonSerializable(typeof(ApiResponse<List<PageDto>>))]
[JsonSerializable(typeof(ApiResponse<List<PageTreeNodeDto>>))]
[JsonSerializable(typeof(ApiResponse<List<CommentDto>>))]
[JsonSerializable(typeof(ApiResponse<PageVersionDto>))]
[JsonSerializable(typeof(ApiResponse<List<PageVersionListDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<UserDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<WorkspaceDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<PageDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<CommentDto>>))]
[JsonSerializable(typeof(ApiResponse<AttachmentDto>))]
[JsonSerializable(typeof(ApiResponse<List<AttachmentListItemDto>>))]
[JsonSerializable(typeof(PagedResponse<UserDto>))]
[JsonSerializable(typeof(PagedResponse<WorkspaceDto>))]
[JsonSerializable(typeof(PagedResponse<PageDto>))]
[JsonSerializable(typeof(PagedResponse<CommentDto>))]
[JsonSerializable(typeof(UserDto))]
[JsonSerializable(typeof(List<UserDto>))]
[JsonSerializable(typeof(WorkspaceDto))]
[JsonSerializable(typeof(List<WorkspaceDto>))]
[JsonSerializable(typeof(PageDto))]
[JsonSerializable(typeof(List<PageDto>))]
[JsonSerializable(typeof(PageTreeNodeDto))]
[JsonSerializable(typeof(List<PageTreeNodeDto>))]
[JsonSerializable(typeof(CommentDto))]
[JsonSerializable(typeof(List<CommentDto>))]
[JsonSerializable(typeof(PageVersionDto))]
[JsonSerializable(typeof(List<PageVersionListDto>))]
[JsonSerializable(typeof(AttachmentDto))]
[JsonSerializable(typeof(AttachmentListItemDto))]
[JsonSerializable(typeof(UserSummaryDto))]
[JsonSerializable(typeof(WorkspaceSummaryDto))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(CreateWorkspaceRequest))]
[JsonSerializable(typeof(UpdateWorkspaceRequest))]
[JsonSerializable(typeof(CreatePageRequest))]
[JsonSerializable(typeof(UpdatePageRequest))]
[JsonSerializable(typeof(CreateCommentRequest))]
[JsonSerializable(typeof(UpdateCommentRequest))]
[JsonSerializable(typeof(PagedRequest))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(ApiInfoResponse))]
[JsonSerializable(typeof(ApiEndpoints))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(ApiResponse<SetupStatusResponse>))]
[JsonSerializable(typeof(ApiResponse<TestConnectionResponse>))]
[JsonSerializable(typeof(SetupStatusResponse))]
[JsonSerializable(typeof(TestConnectionResponse))]
[JsonSerializable(typeof(SetupResponse))]
[JsonSerializable(typeof(DatabaseConfigRequest))]
[JsonSerializable(typeof(SetupRequest))]
[JsonSerializable(typeof(InstalledInfo))]
[JsonSerializable(typeof(ActivityDto))]
[JsonSerializable(typeof(List<ActivityDto>))]
[JsonSerializable(typeof(ApiResponse<SetupResponse>))]
[JsonSerializable(typeof(ApiResponse<OfficePreviewConfigDto>))]
[JsonSerializable(typeof(OfficePreviewConfigDto))]
[JsonSerializable(typeof(SiteConfigDto))]
[JsonSerializable(typeof(DisplayConfigDto))]
[JsonSerializable(typeof(SiteInfoDto))]
[JsonSerializable(typeof(ApiResponse<SiteConfigDto>))]
[JsonSerializable(typeof(ApiResponse<DisplayConfigDto>))]
[JsonSerializable(typeof(ApiResponse<SiteInfoDto>))]
[JsonSerializable(typeof(SecurityConfigDto))]
[JsonSerializable(typeof(ApiResponse<SecurityConfigDto>))]
public partial class AppJsonContext : JsonSerializerContext
{
}
